### ISSUE TITLE
Add tutorial for ts-jest

### ISSUE THREAD

**Issue by anilanar** [userlike/joke#10]
So that ts-jest people know what they need to do.

**Comment by wh1t3cAt1k** [comment]
Probably, in addition to the steps you outlined in # , ts-jest wouldn't know either that many things in babel don't work out of the box:

![image](https://user-images.githubusercontent.com/5159662/89765793-b36cf780-daff-11ea-80fb-2d982baa6ef0.png)

So they'd need to set up preset-env or similar.

**Comment by wh1t3cAt1k** [comment]
For reference, this is the configuration I've set up for my project:

```
globals: {
        'ts-jest': {
            babelConfig: {
                plugins: ['@userlike/babel-plugin-joke'],
                presets: [
                    [
                        '@babel/preset-env',
                        {
                            targets: {
                                node: 'current',
                            },
                        },
                    ],
                ],
            },
            tsConfig: {
                module: 'es2020',
                moduleResolution: 'node',
            },
        },
    },
```

Note that `tsConfig` ES2020 is actually **required** because otherwise it will complain about dynamic import syntax.

**Comment by anilanar** [comment]
Thanks for your great input.

> Note that tsConfig ES2020 or ESNEXT module is actually required because otherwise it will complain about dynamic import syntax, so ES2015 won't work!

Ah I completely forgot about that. Thanks for reminding :love_you_gesture:

**Comment by wh1t3cAt1k** [comment]
I am willing to create a PR to include this into the README if you are open to contributions

**Comment by anilanar** [comment]
@wh1t3cAt1k Sure, please do.
