### ISSUE TITLE
Mock typing can be improved

### ISSUE THREAD

**Issue by wh1t3cAt1k** [userlike/joke#13]
Mockable class:

```typescript
export class Widget {
    public static readonly doWork = async () => ...
}
```

**Actual result:**

The object returned by `mock(import('./widget'))` contains no IntelliSense properties in the typing.

**Expected result:**

Compare with `mocked` helper from `ts-jest/utils`: the object contains the `doWork` property which is typed correctly (both as a function and as a mock).

**Notes**:

As a workaround, I use `mock(import(...` independently (not assigning the result anywhere), and then, when I need to setup mocks, I separately use the `mocked` helper from `ts-jest/utils`, applied to the result of a "normal" import (to get the proper mock typing). 

This is of course not too DRY...

Should we re-use the typings of the `mocked` helper from `ts-jest/utils`? It seems to be comprehensive and to work correctly in all cases.

**Comment by wh1t3cAt1k** [comment]
@anilanar here are the relevant typings from `ts-jest`: https://github.com/kulshekhar/ts-jest/blob/master/src/utils/testing.ts

They never failed me, maybe it's a good idea to pull them? I can do a PR if you wish.

**Comment by anilanar** [comment]
I'm actually planning to add a test infra. for mocked types so that we can safely pick the most appropriate type for it.
