### ISSUE TITLE
Support in ts-jest as a transformer, without babel?

### ISSUE THREAD

**Issue by wh1t3cAt1k** [userlike/joke#8]
Fantastic library. I would love to use it in my project, however we don't directly use babel-jest at all and stick with ts-jest for transformation and typechecking. Should we make an effort to support it as an AST transformer in addition to the babel toolset chain?

https://kulshekhar.github.io/ts-jest/user/config/astTransformers

**Comment by anilanar** [comment]
@wh1t3cAt1k 

I will look into it and see how much work it is to port the babel ast transformation to ts ast transformation.

**Comment by anilanar** [comment]
It seems it is too much work for what it's worth.

I've tested `@userlike/joke` with `ts-jest` + `babel` and it works if tsconfig's `module` is set to `ES*`. 

For those that have `module: commonjs` can just create a `tsconfig.test.json` and do:

```json
{
  "extends": "tsconfig.json",
  "include": ["src/**/*.ts"],
  "exclude": ["src/**/*.test.ts"],
  "compilerOptions": {
    "module": "ES2015"
  }
}
```

**Comment by wh1t3cAt1k** [comment]
Thank you. It's a good idea to add this as a tutorial for someone like me. Thanks @anilanar !
